### ISSUE TITLE
No public license

### ISSUE THREAD

**Issue by 2mac** [mark-me/Pi-Jukebox#1]
There is neither a license file nor any license statement for this software that is apparent to anyone who downloads it.

Please state the terms so that users can know what they are allowed to do.

**Comment by mark-me** [comment]
Hi. Sorry for the really late reply. Just revived the project. Where can I get such a licence to add?

**Comment by 2mac** [comment]
It depends on your philosophy. Do you want someone else to be able to make a proprietary version of your software?

**Comment by mark-me** [comment]
Definitely not. Forking is fine, but open source please. So how do I go about doing that? Your help is much appreciated.

**Comment by 2mac** [comment]
I recommend the GNU Affero General Public License, version 3 (that's AGPL, not just GPL).

**Comment by mark-me** [comment]
I've been reading up on it and the difference between AGPL and GPL makes sense. I've added them. Thanks for your help!

**Comment by 2mac** [comment]
It would be helpful for people visiting your repo if you created a `COPYING` file with the license text of the AGPL.

**Comment by mark-me** [comment]
Thank you for your advice and patience! I added the file.
