### ISSUE TITLE
Exception on loading

### ISSUE THREAD

**Issue by StateDiagram** [mark-me/Pi-Jukebox#3]
Noticed that the wrong setting name was loaded.

Exception trace pointed to screen_settings.py line 169. If I change this line
        label = "Change host: " + config_file.setting_get('MPD Settings', 'Host')
to
        label = "Change host: " + config_file.setting_get('MPD Settings', 'host')
it works.

**Comment by mark-me** [comment]
Thanks for pointing that out. Fixed it in the source code
