### ISSUE TITLE
Not able to configure music directory

### ISSUE THREAD

**Issue by buguibu** [mark-me/Pi-Jukebox#5]
Following the instructions again and again i always get the same error:

> 'No music directory'

I've also tried to hardcode it on **pi-jukebox.py** without success, and in **config_file.py** getting a blank screen.

**Comment by ppsx** [comment]
Seems that your mpd is not configured properly.
You should try to use any commandline mpd client to see if it works.

**Comment by GlodNet** [comment]
Remember that you can always TELNET directly into MPD's control port, thus eliminating one source of "obfuscation" (ie, the MPD client software).

**Comment by mgbiedmawifarer** [comment]
I had a typo in mpd.conf but now have other issue with the touch screen.

**Comment by buguibu** [comment]
I had a typo  in mpd.conf but now it raises a touch screen problem.
